spring.application.name=Backend
server.error.include-stacktrace=never
server.error.include-message=never

spring.datasource.url=jdbc:postgresql://localhost:5432/intelligent_support_db
spring.datasource.username=support_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
python.ai.base-url=${PYTHON_AI_BASE_URL:http://localhost:8000}
